before_install:
- npm update -g npm
cache:
  directories:
  - node_modules
language: node_js
node_js:
- 8
notifications:
  email: false
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
- ./node_modules/.bin/codecov
sudo: false